#!/bin/bash

function find() {
    local tmp
    wmctrl -l -x | grep -Eow "[^ ]*  $2 $1 [^ ]* .*$3" | while read -r line ; do
        echo "$line" | head -c 10 && echo
    done
}

if [ $# -eq 0 ]; then
    echo "Usage: findWindow <CLASS> </DESKTOP> </TITLE>" 1>&2
    exit 1
fi
find "$1" "${2:-[0-9]}" "${3:-.*}"
